version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: woop_db
    environment:
      POSTGRES_USER: woop
      POSTGRES_PASSWORD: woop_password
      POSTGRES_DB: woop_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
